version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
      - image: circleci/mongo:3.4
    environment:
      - NODE_ENV: test
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}
      - run:
          name: Notify build started
          command: |
            BUILD=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            curl -H "Content-Type: application/json" \
            -d '{ "release": "'$BUILD'" }' \
            -X POST https://api-pipeline.dashboardhub.io/environments/c6631f90-de59-11e7-baca-539d2ad633e4/deployed/c66346a0-de59-11e7-baca-539d2ad633e4/startBuild
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Test server
          command: npm run test:server
      - run:
          name: Notify build completed
          command: |
            BUILD=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            curl -H "Content-Type: application/json" \
            -d '{ "release": "'$BUILD'" }' \
            -X POST https://api-pipeline.dashboardhub.io/environments/c6631f90-de59-11e7-baca-539d2ad633e4/deployed/c66346a0-de59-11e7-baca-539d2ad633e4/finishBuild
      - save_cache:
          key: dependency-cache-{{ .Branch }}
          paths:
            - node_modules
